### ISSUE TITLE
Errors installing Electron distributable

### ISSUE THREAD

**Issue by P33J3** [jepiqueau/ionic7-angular-sqlite-starter#1]
The project builds and runs in electron fine.

When I use electron-forge cli to package the app, that also is successful.

But when I try to install the distribution package I get the following errors:

1:

_Unhandled Promise Rejection

Error: ERR_FILE_NOT_FOUND (-6) loading 'capacitor-electron://-/'

at rejectAndCleanup (node:electron/js2c/browser_init:2:84917)

at EventEmitter.failListener (node:electron/js2c/browser_init:2:85130)

at EventEmitter.emit (node:events:513:28)_
2:

Unhandled Promise Rejection

Error: Cannot find module 'C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/build/src/rt/electron-plugins.js'

Require stack:

- C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/electron/node_modules/@capacitor-community/electron/dist/core/index.js

- C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/electron/build/src/index.js

-

at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)

at n._resolveFilename (node:electron/js2c/browser_init:2:117457)

at Module._load (node:internal/modules/cjs/loader:927:27)

at f._load (node:electron/js2c/asar_bundle:2:13330)

at Module.require (node:internal/modules/cjs/loader:1148:19)

at require (node:internal/modules/cjs/helpers:110:18)

at Object.Y (C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/electron/node_modules/@capacitor-community/electron/dist/core/index.js:1:2139)

at ElectronCapacitorApp.init (C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/electron/build/src/setup.js:173:20)

at C:/Users/name/AppData/Local/app-name/app-0.0.1/resources/app.asar/electron/build/src/index.js:41:26
The line at the end of this second error (/build/src/index.js:41:26) is

await myCapacitorApp.init();

After building, the actions I took to package were:

npm run electron:start //mainly so that I know the project has been built.

npm install --save-dev @electron-forge/cli

npx electron-forge import

npm run make

The distributable is made and then I try to install it (this is where the errors happen).

Any assistance is appreciated.

**Comment by P33J3** [comment]
Lessons learned:

In package.json, `"main": `  should be set to the main.js/index.js from the built project folder

I disabled the sqlite as I did not use it and it was causing initialization errors, the module could not be found. I may have commented out something that was necessary for that module to work.

To build, package and make an app using this project:

From root of project

`npm run electron:prepare`
`cd electron`
`npm run electron:pack`
`npm run electron:make` (in the package.json,  `-p always ` will require you to authorize Github; you might as well because otherwise when your app installs it will throw an error because the author was not authenticated. )
